import { useMemo, useState } from 'react'
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { StoryGrid } from '../components/StoryCard'
import { categories, regions, storyContent, stories } from '../data/demoStories'

const Shell = ({ title, children }) => <main className="mx-auto min-h-[60vh] max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><h1 className="mb-2 font-serif text-4xl font-bold text-stone-900">{title}</h1>{children}</main>
export function Explore() { const [params] = useSearchParams(); const [query, setQuery] = useState(''); const [region, setRegion] = useState(params.get('region') || ''); const filtered = useMemo(() => stories.filter((s) => (!region || s.region === region) && s.title.toLowerCase().includes(query.toLowerCase())), [query, region]); return <Shell title="Jelajahi Cerito"><p className="mb-8 text-[#6b3f20]">Temukan cerito demo berdasarkan daerah dan kategori.</p><div className="mb-8 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={(e) => setQuery(e.target.value)} className="rounded-xl border border-stone-300 bg-white px-4 py-3" placeholder="Cari cerito..." /><select value={region} onChange={(e) => setRegion(e.target.value)} className="rounded-xl border border-stone-300 bg-white px-4 py-3"><option value="">Semua daerah</option>{regions.map((x) => <option key={x}>{x}</option>)}</select></div><StoryGrid stories={filtered} /></Shell> }
export function StoryDetail() { const { id } = useParams(); const story = stories.find((x) => x.id === id); if (!story) return <Shell title="Cerito tidak ditemukan"><Link to="/jelajahi" className="text-[#9a3412]">Kembali menjelajah</Link></Shell>; const content = storyContent[story.id]; return <main><img src={story.image} alt={story.title} className="h-64 w-full object-cover brightness-75 sm:h-[390px]" /><article className="mx-auto max-w-3xl px-4 py-14 sm:px-6"><p className="text-sm font-semibold text-[#9a3412]">{story.category} · {story.region}</p><h1 className="mt-2 font-serif text-3xl font-bold text-stone-900 sm:text-4xl">{story.title}</h1><p className="mt-8 leading-8 text-stone-700">{content.summary}</p><h2 className="mt-10 font-serif text-2xl font-bold">Pesan Moral</h2><p className="mt-3 text-stone-700">{content.moral}</p></article></main> }
export function MapPage() { return <Shell title="Peta Cerito"><p className="mb-8 text-[#6b3f20]">Persebaran lokasi demo di Sumatera Selatan.</p><div className="h-[520px] overflow-hidden rounded-3xl border border-[#e8dfd1]"><MapContainer center={[-3.2, 104.3]} zoom={7} className="h-full w-full"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{[{name:'Palembang',pos:[-2.99,104.76]},{name:'Lahat',pos:[-3.78,103.54]},{name:'Pagar Alam',pos:[-4.02,103.25]}].map((x) => <Marker position={x.pos} key={x.name}><Popup>{x.name}<br />Lokasi demo.</Popup></Marker>)}</MapContainer></div></Shell> }
export function AIPage() { const [question, setQuestion] = useState(''); const submit = (e) => { e.preventDefault(); if (question) setQuestion('') }; return <Shell title="Tanya Cerito"><p className="mb-8 max-w-2xl text-[#6b3f20]">Asisten belum terhubung ke AI. UI ini siap disambungkan ke service AI terverifikasi.</p><form onSubmit={submit} className="flex max-w-3xl gap-2"><input value={question} onChange={(e) => setQuestion(e.target.value)} className="min-w-0 flex-1 rounded-2xl border border-stone-300 bg-white px-5 py-4" placeholder="Tulis pertanyaanmu..." /><button className="rounded-2xl bg-[#9a3412] px-6 py-4 font-semibold text-white">Kirim</button></form></Shell> }
export function Recommendation() { const [interest, setInterest] = useState('Legenda'); return <Shell title="Rekomendasi Cerito"><p className="mb-6 text-[#6b3f20]">Pilih minatmu untuk rekomendasi demo berbasis kategori.</p><div className="mb-8 flex flex-wrap gap-2">{categories.map((x) => <button key={x} onClick={() => setInterest(x)} className={`rounded-full px-4 py-2 text-sm ${interest === x ? 'bg-[#9a3412] text-white' : 'bg-white border border-stone-300'}`}>{x}</button>)}</div><StoryGrid stories={stories.filter((x) => x.category === interest)} /></Shell> }
export function Gallery() { return <Shell title="Galeri"><p className="mb-8 text-[#6b3f20]">Koleksi ilustrasi demo dari desain referensi.</p><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{stories.map((x) => <img key={x.id} src={x.image} alt={x.title} className="h-64 w-full rounded-2xl object-cover" />)}</div></Shell> }
export function About() { return <Shell title="Tentang Cerito Wong Dulu"><p className="max-w-2xl text-lg leading-8 text-stone-700">Cerito Wong Dulu adalah platform digital untuk melestarikan cerita rakyat Sumatera Selatan.</p></Shell> }
export function AdminDashboard() { return <Shell title="Admin"><p className="text-[#6b3f20]">Akses admin memerlukan autentikasi Supabase serta role ADMIN. Konfigurasi proyek Supabase diperlukan sebelum panel CRUD diaktifkan.</p></Shell> }
